version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    image: coffee-server
    container_name: coffee-node-server
    command: /usr/src/app/node_modules/.bin/nodemon index.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
      - "27017:27017"
    env_file: 
      - .env
    networks:
      - app-network
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    image: coffee-client
    container_name: coffee-react-client
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local